### ISSUE TITLE
Plausible deniability improvement / custom impl

### ISSUE THREAD

**Issue by Zytekaron** [sunknudsen/blockcrypt#4]
I decided to write my own implementation of this scheme to play around with it and see if I could make any meaningful changes. I came up with shuffling blocks as the biggest change which could improve privacy, and at the time I hadn't noticed issue #3. It seems I hit the nail on the head with my impl for the first issue.

I also made some other unimportant design choices which can be ignored, like using aes-256-ctr (probably worse), and exporting to json. I only did this to make it easier for me to implement, as I'm also no security researcher or expert, just a hobby sec dev right now.

Here's what I came up with:
https://gist.github.com/Zytekaron/beae99b3e9a69a7ad76cbeec54347d21

**Comment by sunknudsen** [comment]
Hey @Zytekaron, thanks for contributing to Blockcrypt… see https://github.com/sunknudsen/blockcrypt/issues/3 to join conversation about shuffling.
